### ISSUE TITLE
Can't run app.py

### ISSUE THREAD

**Issue by Dorteel** [leolani/eliza-parent#1]
I get the following error:
```console
(venv) (base) user@dorteel:~/Repos/eliza-parent/cltl-eliza-app/py-app$ python3 app.py
Traceback (most recent call last):
  File "app.py", line 13, in <module>
    from cltl.backend.server import BackendServer
  File "/home/user/Repos/eliza-parent/cltl-eliza-app/venv/lib/python3.8/site-packages/cltl/backend/server.py", line 3, in <module>
    import flask
  File "/home/user/Repos/eliza-parent/cltl-eliza-app/venv/lib/python3.8/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask
  File "/home/user/Repos/eliza-parent/cltl-eliza-app/venv/lib/python3.8/site-packages/flask/app.py", line 32, in <module>
    from werkzeug.wrappers import BaseResponse
ImportError: cannot import name 'BaseResponse' from 'werkzeug.wrappers' (/home/user/Repos/eliza-parent/cltl-eliza-app/venv/lib/python3.8/site-packages/werkzeug/wrappers/__init__.py)
```

Tried downgrading Flask, but it didn't work.

**Comment by numblr** [comment]
Hey,

I'll push a fix, actually you need to downgrade Werkzeug to 2.0.3.

Am Do., 31. März 2022 um 15:42 Uhr schrieb Dorteel ***@***.***

**Comment by numblr** [comment]
I pinned the Werkzeug version in cltl-requirements. I think there is still a bug in the makefiles, so it will not automatically pick up the change, but removing the venv folder from cltl-eliza-app and building again should fix it:
```
rm -rf cltl-eliza-app/venv
make build
```
from the eliza-parent.

**Comment by Dorteel** [comment]
Thanks! removing the venv folder and building again didn't work, but manually downgrading it to 2.0.3 solved it!
